# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

P_4pl <- function(delta, alpha, theta, la, ua) {
    .Call('PP_P_4pl', PACKAGE = 'PP', delta, alpha, theta, la, ua)
}

P_4pl4wle <- function(delta, alpha, theta, la, ua) {
    .Call('PP_P_4pl4wle', PACKAGE = 'PP', delta, alpha, theta, la, ua)
}

L4pl <- function(awm, DELTA, ALPHA, CS, DS, THETA, map, mu, sigma2) {
    .Call('PP_L4pl', PACKAGE = 'PP', awm, DELTA, ALPHA, CS, DS, THETA, map, mu, sigma2)
}

L4pl_wle <- function(awm, DELTA, ALPHA, CS, DS, THETA) {
    .Call('PP_L4pl_wle', PACKAGE = 'PP', awm, DELTA, ALPHA, CS, DS, THETA)
}

NR_4PL <- function(awm, DELTA, ALPHA, CS, DS, THETA, wm, maxsteps, exac, mu, sigma2) {
    .Call('PP_NR_4PL', PACKAGE = 'PP', awm, DELTA, ALPHA, CS, DS, THETA, wm, maxsteps, exac, mu, sigma2)
}

P_gpcm <- function(delta, alpha, theta, resp) {
    .Call('PP_P_gpcm', PACKAGE = 'PP', delta, alpha, theta, resp)
}

L12gpcm <- function(awm, DELTA, ALPHA, THETA, mu, sigma2, map) {
    .Call('PP_L12gpcm', PACKAGE = 'PP', awm, DELTA, ALPHA, THETA, mu, sigma2, map)
}

Pcorr1_gpcm <- function(delta, alpha, theta) {
    .Call('PP_Pcorr1_gpcm', PACKAGE = 'PP', delta, alpha, theta)
}

L12gpcm_wle <- function(awm, DELTA, ALPHA, THETA) {
    .Call('PP_L12gpcm_wle', PACKAGE = 'PP', awm, DELTA, ALPHA, THETA)
}

NR_GPCM <- function(awm, DELTA, ALPHA, THETA, wm, maxsteps, exac, mu, sigma2) {
    .Call('PP_NR_GPCM', PACKAGE = 'PP', awm, DELTA, ALPHA, THETA, wm, maxsteps, exac, mu, sigma2)
}

Lgpcm4pl_mle <- function(awm, DELTA, ALPHA, CS, DS, THETA, model, mu, sigma2, map) {
    .Call('PP_Lgpcm4pl_mle', PACKAGE = 'PP', awm, DELTA, ALPHA, CS, DS, THETA, model, mu, sigma2, map)
}

Lgpcm4pl_wle <- function(awm, DELTA, ALPHA, CS, DS, THETA, model) {
    .Call('PP_Lgpcm4pl_wle', PACKAGE = 'PP', awm, DELTA, ALPHA, CS, DS, THETA, model)
}

NR_mixed <- function(awm, DELTA, ALPHA, CS, DS, THETA, model, wm, maxsteps, exac, mu, sigma2) {
    .Call('PP_NR_mixed', PACKAGE = 'PP', awm, DELTA, ALPHA, CS, DS, THETA, model, wm, maxsteps, exac, mu, sigma2)
}

ansol <- function(awm, maxsc) {
    .Call('PP_ansol', PACKAGE = 'PP', awm, maxsc)
}

